services:
    CleverAge\CacheProcessBundle\Transformer\:
        resource: '../../src/Transformer/*'
        autowire: true
        public: false
        arguments:
            $cache: '@cache.app'
        tags:
            - { name: cleverage.transformer }
            - { name: monolog.logger, channel: cleverage_process_transformer }
