services:
    CleverAge\CacheProcessBundle\Task\:
        resource: '../../../Task/*'
        autowire: true
        public: true
        shared: false
        arguments:
            $cache: '@cache.app'
        tags:
            - { name: monolog.logger, channel: cleverage_process_task }
